### ISSUE TITLE
builds of `fleet` are broken on linux

### ISSUE THREAD

**Issue by efronlicht** [dimensionhq/fleet#10]
Building the fleet executable through Cargo (in the natural way (eg, `git clone; cd fleet; cargo build`)doesn't work.
Even after installing `sccache` and `lld`, the builds are broken, because your `config.toml` expects `sccache` at `C:\Users\potti\.cargo\bin`.

```sh
cargo build
```
```
 cargo build                                                                 
error: failed to run `rustc` to learn about target-specific information

Caused by:
  could not execute process `C:\Users\potti\.cargo\bin\sccache rustc - --crate-name ___ --print=file-names -Clink-arg=-fuse-ld=lld -Zshare-generics=y --crate-type bin --crate-type rlib --crate-type dylib --crate-type cdylib --crate-type staticlib --crate-type proc-macro --print=sysroot --print=cfg` (never executed)

Caused by:
  No such file or directory (os error 2)
```
this is fixable by simply deleting that line in the config, or by deleting the config entirely.

if you want people to take this project more seriously, I strongly suggest making some kind of basic CI that tests the builds on "bare" ubuntu, alpine, & windows, by following your readme exactly.

you should list your dependencies in the README, too: AFAIK, they're:

### sccache
`cargo install sccache`
#### windows
`winget install llvm`
#### ubuntu
`sudo apt-get install lld-12`
### zld (macos)
`brew install zld`

**Comment by suptejas** [comment]
@efronlicht You need to run `fleet build` to update the configuration files, use `fleet build` instead of cargo build.

**Comment by suptejas** [comment]
The docs state that you need to use `fleet build` and `fleet run` instead of the cargo cli, fleet applies all the required configurations and then runs your optimized build through `cargo` internally.

**Comment by efronlicht** [comment]
I can't run `fleet build` if I don't have fleet.

**Comment by efronlicht** [comment]
These are your instructions from your README.md:

<img width="763" alt="image" src="https://user-images.githubusercontent.com/26349352/164914444-3dc2cfcc-0c4d-46b7-9bd2-305c42388ab0.png">

**Comment by VarunPotti** [comment]
Hey @efronlicht, the cargo install command installs cargo from source, the command `fleet` should work fine, so we would recommend you to use the command fleet so that it would update the values under `.cargo/config.toml`. So please try running `fleet run` (its already installed)

**Comment by efronlicht** [comment]
I can see my input is not wanted. I'll see you around.

**Comment by suptejas** [comment]
@efronlicht I understand what you mean, we're working on fixing it up right now.

**Comment by suptejas** [comment]
@efronlicht It should be fixed now, we removed the `.cargo` directory since it's not possible to build from source without Fleet already installed.

**Comment by efronlicht** [comment]
Excellent, thank you! Should probably be in `.gitignore` so that can't happen again.

**Comment by suptejas** [comment]
Good idea, I'll do that ASAP!

**Comment by VarunPotti** [comment]
Thank you for bringing this up 😁 and we are really sorry about that.

**Comment by suptejas** [comment]
All done!

**Comment by efronlicht** [comment]
I'd reiterate here that some kind of basic CI & merge policy would help prevent these kinds of problems. AFAIK you are pushing directly to master without any safeguards. This is convenient, but it's also a great way to unknowingly break builds and end up with frustrated users.

**Comment by efronlicht** [comment]
Thank you for responding promptly.
