### ISSUE TITLE
Fleet doesn't work if rustup is installed via scoop

### ISSUE THREAD

**Issue by Milo123459** [dimensionhq/fleet#11]
**Describe the bug**

It cannot find sccache because it is in a custom directory. A good environment variable to look for is `$CARGO_HOME`.

**To Reproduce**
1. Run `fleet run`
2. Sccache is installed but it warns about not being installed
3. 
**Expected behavior**

It should find sccache in the custom cargo directory.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows
 - Version: 11

**Additional context**

**Comment by VarunPotti** [comment]
Hey @Milo123459, can you send the version of fleet by running `fleet --version`? We recently patched this and we would recommend updating to fleet v0.0.6 (by running `cargo install fleet-rs -f`).

**Comment by Milo123459** [comment]
<img width="646" alt="image" src="https://user-images.githubusercontent.com/50248166/164915848-607ad519-cd5d-46e9-90f8-e45e805841ba.png">

I actually cannot check what version I am running. This seems like a bug and should probably be fixed.

**Comment by Milo123459** [comment]
Well, that image depicts the bug. Sccache is installed:
<img width="655" alt="image" src="https://user-images.githubusercontent.com/50248166/164915869-a99ec5db-a0b6-4702-9fcd-332abd786a5d.png">

**Comment by VarunPotti** [comment]
Yep, the earliest versions of fleet where not shipped with `fleet --version`, it has been fixed now (both version flag and resolving sccache), so I would recommend updating to v0.0.6 it must be fixed over there.

**Comment by suptejas** [comment]
@Milo123459 Can you confirm this is resolved for you?

**Comment by Milo123459** [comment]
<img width="941" alt="image" src="https://user-images.githubusercontent.com/50248166/164916250-7beb23b6-6760-4670-b638-bde1b7348689.png">

Seems this issue is fixed, but I'm getting this now

**Comment by suptejas** [comment]
Is `sccache` installed?

**Comment by Milo123459** [comment]
Yeah..

**Comment by suptejas** [comment]
Could you check if the path mentioned at the beginning of the error exists?

**Comment by VarunPotti** [comment]
oh I see the issue, working on the fix right now!

**Comment by Milo123459** [comment]
Ah, found the issue. It should be checking inside of $CARGO_HOME/bin not $CARGO_HOME.

**Comment by VarunPotti** [comment]
yep

**Comment by VarunPotti** [comment]
Fixed! You shd be able to use fleet now by running `cargo install fleet-rs -f`

**Comment by Milo123459** [comment]
Yup, works!
