### ISSUE TITLE
Working with multiple people in a team

### ISSUE THREAD

**Issue by Milo123459** [dimensionhq/fleet#18]
This repo gitignores `.cargo/config` - a file that contains general configuration for the project. If you don't gitignore it, you will constantly have changes in the `.cargo/config` as it is updating paths to work on that specific machine. Are there anyways to make it so we don't have to gitignore `.cargo/config`, but continue to use fleet?

**Comment by suptejas** [comment]
Fleet automatically updates the paths inside `.cargo/config`

**Comment by suptejas** [comment]
As long as you use `fleet [command]` it will automatically update everything it needs to.

**Comment by Milo123459** [comment]
The problem with this is that it puts that in the `.cargo/config` file which is checked into git. This means that every time someone from a different device makes a change, that file will change.

**Comment by Milo123459** [comment]
Another thing, what about contributing to projects, but you want to get the benefits of fleet? You would have to change the file, and then manually undo those changes.

**Comment by lucasfernog** [comment]
If you never use the .cargo/config.toml file you can set up a global gitignore.

**Comment by Milo123459** [comment]
Yeah, that would work *if you never use it*. The key point here is that my entire team uses this file and has lots of important aliases and other things.
