### ISSUE TITLE
Allow clang from different locations (not only `/usr/bin/clang`)

### ISSUE THREAD

**Issue by jianshu93** [dimensionhq/fleet#19]
on a linux server, where I do not have sudo access:

error: linker `/usr/bin/clang` not found
  |
  = note: No such file or directory (os error 2)

error: could not compile `rayon-core` due to previous error
warning: build failed, waiting for other jobs to finish...
error: could not compile `log` due to previous error
error: could not compile `crossbeam-epoch` due to previous error
error: could not compile `parking_lot_core` due to previous error
error: could not compile `memchr` due to previous error
error: could not compile `getrandom` due to previous error
error: could not compile `crossbeam-utils` due to previous error
error: could not compile `proc-macro-hack` due to previous error
error: could not compile `proc-macro2` due to previous error
error: could not compile `serde_derive` due to previous error
error: could not compile `libc` due to previous error
error: could not compile `serde` due to previous error
error: could not compile `syn` due to previous error
=> You have not installed `lld`. Run `sudo apt install lld`.
=> You have not installed `clang`. Run `sudo apt install clang`.

I do have those 2 installed but is not in /usr/bin:

/usr/local/pace-apps/spack/packages/0.13/linux-rhel7-x86_64/gcc-4.8.5/intel-parallel-studio-cluster.2019.5-rde2uvgb2mq2x6obqaklxppmycfngjgm/compilers_and_libraries_2019.5.281/linux/bin/lld
[jzhao399@atl1-1-03-004-19-l hnswlib-rs]$ which clang
/usr/local/pace-apps/spack/packages/0.13/linux-rhel7-x86_64/gcc-4.8.5/intel-parallel-studio-cluster.2019.5-rde2uvgb2mq2x6obqaklxppmycfngjgm/compilers_and_libraries_2019.5.281/linux/bin/clang

why depend on a system level clang and lld? Think about those who wants to install via conda et.al.

Thanks,
Jianshu

**Comment by suptejas** [comment]
Thanks for pointing this issue, we'll address it soon.

**Comment by aathif394** [comment]
How about using an environment variable to specify the desired clang path, like `FLEET_CLANG_DIR`?

**Comment by VarunPotti** [comment]
Right now what we thought for release [v1.0.0](https://github.com/orgs/dimensionhq/projects/2) is a global config file (`~/.config/fleet/base.toml`) over there you can override the settings (clang path, whether you want to use mold/lld, etc), other than this if the value in the config file is not present we run `which/where clang` and then get the path. So I don't think an environment variable is required as of now.

**Comment by GrinderDeveloper** [comment]
This issue has seemed to be fixed. If this issue re-occurs, or you’d like to open another issue, please create one! If you feel like it needs to be reopened, reach out to me over at our Discord Server (https://discord.gg/RsTeV6rpqJ).

Grinder (Community Manager)

**Comment by VarunPotti** [comment]
Looks like this issue has been fixed, closing.
