### ISSUE TITLE
Strange configuration after install/uninstall fleet

### ISSUE THREAD

**Issue by jianshu93** [dimensionhq/fleet#20]
Team,

After install and uninstall fleet, I always have the following error no matter what I compile:

error: failed to run `rustc` to learn about target-specific information

Caused by:
  could not execute process `/Users/jianshuzhao/.cargo/bin/sccache rustc - --crate-name ___ --print=file-names --crate-type bin --crate-type rlib --crate-type dylib --crate-type cdylib --crate-type staticlib --crate-type proc-macro --print=sysroot --print=cfg` (never executed)

Caused by:
  No such file or directory (os error 2)

I believe sccache is not required before. What happened to fleet and what configuration was changed?

This is really confusing and not acceptable.

Thanks,

Jianshu

**Comment by jianshu93** [comment]
you have to remove the .cargo folder in the directory when you build using fleet. This is really a bug that should be mentioned.

**Comment by suptejas** [comment]
Hi @jianshu93 , sorry you faced this issue. Is there any reason why you uninstalled `fleet`? Also, the only thing fleet generates is the `.cargo` directory. Although we do agree that there should be documentation added to the website, we're still very early stage and there are more pressing issues to be resolved.

If you ever have the time, feel free to drop a PR into https://github.com/dimensionhq/fleet-docs.

Have a great day.

**Comment by jianshu93** [comment]
Thanks！it is solved afer running a diff of the folder before and after. I uninstalled it because clang and lld is always linked via /usr/bin/clang but not a binary in the path. 

Thanks，

Jianshu
