### ISSUE TITLE
Garbled characters on Windows cmd

### ISSUE THREAD

**Issue by hzqd** [dimensionhq/fleet#36]
**Describe the bug**

Garbled characters on Windows cmd

**To Reproduce**
1. execute `cargo install --git https://github.com/dimensionhq/fleet fleet-rs`
2. execute `fleet`

**Expected behavior**
no garbled

**Screenshots**

![QQ截图20220428145330](https://user-images.githubusercontent.com/40200761/165694418-e8ee8ade-82ac-41c0-b128-84e361dfb377.png)

**Desktop (please complete the following information):**
 - OS: Windows 10

**Additional context**
No additional context

**Comment by suptejas** [comment]
Looks like we might need to enable ansi support on CMD.
