### ISSUE TITLE
Tools reported not found were already installed available. Also not all linux have uses apt as package manager. 

### ISSUE THREAD

**Issue by Abhinav1217** [dimensionhq/fleet#38]
**Describe the bug**
I was trying to install fleet, and I noticed following messages which prompted me to terminate the execution.
![Screenshot from 2022-04-30 19-06-43](https://user-images.githubusercontent.com/740584/166107999-446c097e-9584-4521-8e32-0f36c4735e29.png)
 
It seems that using installer is unable to determine which distro is being used, and assumed it to be a debian based, thus running apt command. I am on Solus OS which uses `eopkg`, Under such condition, installer should inform the user that packages needed to be installed, and then exit safely. 

1. I checked, and both lld and clang are already installed in the system and in the $PATH . So Installer being not able to detect packages is a bug.
![Screenshot from 2022-04-30 19-19-06](https://user-images.githubusercontent.com/740584/166108290-a9753ed8-e70d-489f-9817-46eb584645b3.png)

2. The installer, went on to install rust nightly using rustup, even though I am already on nightly version which is updated frequently. 
![Screenshot from 2022-04-30 19-23-24](https://user-images.githubusercontent.com/740584/166108373-8c8df2ea-4fe7-4669-a0cd-1f6cb3e0ee3b.png)

**Expected behavior**

It should be able to find lld and clang and other tools, if they wasn't installed, installer should install them using appropriate package manager of the distro, or let the user know they need to install tools and exit.

**Desktop (please complete the following information):**
 - Solus OS with Gnome DE.

**Comment by VarunPotti** [comment]
Hey @Abhinav1217 we have added more configuration options to our roadmap ([v1 release](https://github.com/orgs/dimensionhq/projects/2#card-81331011) ) we will be fixing this issue over there.
