### ISSUE TITLE
A Shout Out

### ISSUE THREAD

**Issue by juicycleff** [dimensionhq/fleet#42]
@suptejas really impressed with your rust skill and product development at large for a 16yr old. Really impressed with your products. I also started programming at age 13. You've done what I never had the opportunity to do that young. Keep it up and the fleet is great I use it daily.

**Comment by suptejas** [comment]
Hey! Thank you so much @juicycleff , I appreciate all the kind words - it means a lot to me ❤️ . None of this would be possible without the support of my amazing co-founder @VarunPotti (he's 14 by the way) and our incredible contributors!

Glad you're enjoying fleet, we have more incredible things coming soon!

**Comment by GrinderDeveloper** [comment]
Thanks for your encouragement! You can contact the team, post messages and chat with our yea, over at our discord server https://discord.gg/RsTeV6rpqJ or our Twitter account (@heydimension). Thank you!

Grinder (Community Manager)

**Comment by juicycleff** [comment]
Wow and @VarunPotti is 14, I thought I was cool at that age, but you guys are rocking it. It's great to know we have young people like the both of you doing what you're doing. And when the time comes for contracting some Rust projects, you guys are on my top list that is if your company is open to that kind of work.

But again super impressed by what you guys are doing. There's so much to accomplish and you guys have what it takes.
