### ISSUE TITLE
fleet-rs Crash Report

### ISSUE THREAD

**Issue by bdmorin** [dimensionhq/fleet#44]
**Describe the bug**
using fleet to build wezterm on a chromebook
Linux penguin 5.10.114-16023-g49367ce3348c #1 SMP PREEMPT Mon May 30 19:31:09 PDT 2022 aarch64 GNU/Linux

debian 11 bullseye
cargo 1.61.0 (a028ae4 2022-04-29)
rustc 1.61.0 (fe5b13d68 2022-05-18)

**To Reproduce**
Follow build steps here
https://wezfurlong.org/wezterm/install/source.html

used `fleet build -- --release` and `fleet build` 
produced crash files, attached. 

**Expected behavior**
A rust build

The dump files say `permission denied` but I can't figure out what file. 

[Archive.zip](https://github.com/dimensionhq/fleet/files/8849999/Archive.zip)
(GitHub doesn't allow .toml uploads)

For what it's worth, `cargo build --release` didn't work either. So, I'm just submitting the crash report.

**Comment by VarunPotti** [comment]
Having a look at this right now. Will let you know if I have any updates.

**Comment by VarunPotti** [comment]
Ok so from what I see over here you use a HDD, fleet tries to create a ramdisk and it doesn't work. Please try the below steps and  tell if it still crashes
i) Go to the pwd of your project
ii) Get the fleet_id from `fleet.toml` file
ii) rm -rf /dev/shm/<fleet-id>
iii) rm -rf target
iv) fleet run
