### ISSUE TITLE
How do you uninstall Fleet? Its not working on mac & can't revert

### ISSUE THREAD

**Issue by AppyCat** [dimensionhq/fleet#46]
Hi, I tried Fleet on my mac & get the following error:

error: failed to run `rustc` to learn about target-specific information

Caused by:
  process didn't exit successfully: `/Users/test/.cargo/bin/sccache rustc - --crate-name ___ --print=file-names -C link-arg=-fuse-ld=/usr/local/bin/zld -Zshare-generics=y -Csplit-debuginfo=unpacked --crate-type bin --crate-type rlib --crate-type dylib --crate-type cdylib --crate-type staticlib --crate-type proc-macro --print=sysroot --print=cfg` (exit status: 1)
  --- stderr
  error: the option `Z` is only accepted on the nightly compiler

So Cargo no longer runs. I tried uninstalling & reinstalling rust, but its still not back to the original state.

My rust version is set to stable now instead of nightly.

Appreciate feedback on how to get my mac to prior state & working ref cargo run & cargo build.

Have removed /.cargo and /.rustup, reinstalled Rust to current stable, but cargo run still not working.

**Comment by VarunPotti** [comment]
Hey @AppyCat, fleet needs you to use the nightly version of rust, however we are actively working on getting fleet to work with the stable version of rust. To uninstall fleet you can:
i) `cargo uninstall fleet-rs` 
ii) `cargo uninstall sccache` 
iii) Remove any `.cargo` directory & `fleet.toml` file in projects
