### ISSUE TITLE
[BUG] Fleet's installer assumes your Linux system is Debian-based

### ISSUE THREAD

**Issue by T-O-R-U-S** [dimensionhq/fleet#50]
It attempts to use `apt` regardless of the system you're on. I had to install `lld` manually on my Arch system (`clang` was preinstalled).

**Comment by numfin** [comment]
also no error that i dont have lld. I found this issue and installe lld - and now everything worked

**Comment by VarunPotti** [comment]
This has been fixed in the latest development versions of the installer (see [installer/src/main.rs](https://github.com/dimensionhq/fleet/blob/master/installer/src/main.rs#L86). Once we decide to release v1 we will be updating the installer in the cdn.
