### ISSUE TITLE
Fleet runs apt even on Arch Linux

### ISSUE THREAD

**Issue by arijit79** [dimensionhq/fleet#6]
**Describe the bug**
Fleet runs the `apt` command to install `clang` and `lld` even on Arch Linux which is a non-Debian/Ubuntu based Linux distro. It's offical  package manager is called `pacman`. Also it is kinda bad practice to call `sudo` explicitly by a program.

**To Reproduce**
```sh
curl -L get.fleet.rs | sh
```

**Expected behavior**
I think fleet should ask the user to install `clang` and `lld` by themselves rather doing it by itself.

**Desktop**
 - OS: Arch Linux

**Comment by icepie** [comment]
Hi! I have it work with aur! (https://aur.archlinux.org/packages/fleet-rust)

**Comment by suptejas** [comment]
That's awesome!

**Comment by omac777** [comment]
For Fedora Silverblue, 
`sudo rpm-ostree install lld clang`

**Comment by arijit79** [comment]
That's exactly what the problem is. Either you package it up for every single distribution or ask the user to explicitly install all the dependencies. I think the 2nd route is better as even the official rust-lang/rust repo also asks the users to install the required dependencies before installing `rustup`. This drops the hard coded usage of `apt` and `sudo`.

**Comment by GrinderDeveloper** [comment]
This issue has seemed to be fixed. If this issue re-occurs, or you’d like to open another issue, please create one! If you feel like it needs to be reopened, reach out to me over at our Discord Server (https://discord.gg/RsTeV6rpqJ).

Grinder (Community Manager)

**Comment by VarunPotti** [comment]
Must be fixed s to [#50 (comment)](https://github.com/dimensionhq/fleet/issues/50#issuecomment-1186390267)
