### ISSUE TITLE
fleet run fail, and cargo run fail too

### ISSUE THREAD

**Issue by govo** [dimensionhq/fleet#7]
After install on Mac(M1), get an error when fleet run:

```
main-2588b02f17a95c9e" "-Wl,-dead_strip" "-nodefaultlibs" "-fuse-ld=/usr/local/bin/zld"
  = note: clang: error: invalid linker name in argument '-fuse-ld=/usr/local/bin/zld'
```

and also the cargo command fail after installing fleet:

```
8b02f17a95c9e" "-Wl,-dead_strip" "-nodefaultlibs" "-fuse-ld=/usr/local/bin/zld"
  = note: clang: error: invalid linker name in argument '-fuse-ld=/usr/local/bin/zld'
```

It means both fleet and cargo is broken.

Is there any way to fix it? Thank you!

**Comment by govo** [comment]
I fix the cargo problem by removing .cargo/ in the project.

**Comment by VarunPotti** [comment]
Hey @govo, we use zld to get much faster builds on MacOS, however over here I don't think zld is installed, I would recommend running `brew install michaeleisel/zld/zld`

**Comment by suptejas** [comment]
If you can confirm that installing `zld` fixes the issue for you , then we'll close this issue 😄 .
