### ISSUE TITLE
Looks like the domain is gone

### ISSUE THREAD

**Issue by chenrui333** [dimensionhq/fleet#77]
👋 looks like the fleet.rs domain is gone, see this archive snapshot, [https://web.archive.org/web/20230705002130/http://fleet.rs/.](https://web.archive.org/web/20230705002130/http://fleet.rs/.) Thanks!

**Comment by 1366613** [comment]
@chenrui333 Duplicate, see https://github.com/dimensionhq/fleet/issues/66
